/* KUMAGO 家具家電租賃 — landing page interactions */
(function () {
  "use strict";

  /* ---- sticky header shadow ---- */
  const header = document.querySelector(".site-header");
  const onScroll = () => header.classList.toggle("scrolled", window.scrollY > 8);
  onScroll();
  window.addEventListener("scroll", onScroll, { passive: true });

  /* ---- mobile nav toggle ---- */
  const toggle = document.getElementById("navToggle");
  const nav = document.getElementById("nav");
  const closeNav = () => {
    nav.classList.remove("open");
    toggle.classList.remove("open");
    toggle.setAttribute("aria-expanded", "false");
  };
  toggle.addEventListener("click", () => {
    const open = nav.classList.toggle("open");
    toggle.classList.toggle("open", open);
    toggle.setAttribute("aria-expanded", String(open));
  });
  nav.querySelectorAll("a").forEach((a) => a.addEventListener("click", closeNav));

  /* ---- language toggle (zh-Hant ⇄ ja ⇄ en) ----
     Each language now lives at its own crawlable URL (/ = zh-Hant, /ja, /en —
     generated by tools/build_i18n.js), so the toggle navigates instead of
     swapping strings in place. Current language comes from <html lang>. */
  const langBtn = document.getElementById("langToggle");
  const LANG_PATH = { zh: "/", ja: "/ja", en: "/en" };
  const currentLang = { "zh-Hant": "zh", ja: "ja", en: "en" }[document.documentElement.lang] || "zh";

  if (langBtn) {
    langBtn.querySelectorAll(".lang-opt").forEach((opt) =>
      opt.addEventListener("click", () => {
        const lang = opt.dataset.lang;
        if (lang === currentLang || !LANG_PATH[lang]) return;
        window.location.href = LANG_PATH[lang] + window.location.hash;
      })
    );
  }

  /* ---- scroll reveal ---- */
  const revealTargets = document.querySelectorAll(
    ".section-head, .cat-card, .feature, .step, .product, .quote, .stats, .hero-copy, .hero-visual, .cta-text, .cta-line-card"
  );
  revealTargets.forEach((el, i) => {
    el.classList.add("reveal");
    el.style.transitionDelay = (i % 4) * 70 + "ms";
  });

  if ("IntersectionObserver" in window) {
    const io = new IntersectionObserver(
      (entries, obs) => {
        entries.forEach((e) => {
          if (e.isIntersecting) {
            e.target.classList.add("in");
            obs.unobserve(e.target);
          }
        });
      },
      { threshold: 0.12, rootMargin: "0px 0px -40px 0px" }
    );
    revealTargets.forEach((el) => io.observe(el));
  } else {
    revealTargets.forEach((el) => el.classList.add("in"));
  }

})();
